server:
  port: 8889
  servlet:
    context-path: /
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 256
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true


  compression:
    #  开启压缩
    enabled: true
spring:
  # 模板引擎配置
  thymeleaf:
    mode: HTML
    encoding: utf-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 总文件大小
      max-request-size: 20MB
system:
  copyright-year: 2019-2022
  version: 1.0

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: not_empty
      select-strategy: not_empty
      update-strategy: not_empty

  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
fastjava:
  logger:
    enable: true
    print: true
  spring:
    security:
      ignoring-login-url:
        - /favicon.ico**
        - /ruoyi.png**
        - /html/**
        - /css/**
        - /docs/**
        - /fonts/**
        - /img/**
        - /ajax/**
        - /js/**
        - /ruoyi/**
        - /actuator/**
        #      - /oauth/token
        - /token/**
        - /login
